steps:
  - name: node
    entrypoint: npm
    args: ["install"]
  - name: node
    entrypoint: npm
    args: ["run", "clean"]
  - name: node
    entrypoint: npm
    args: ["run", "build"]
  - name: gcr.io/cloud-builders/gsutil
    args:
      - "-m"
      - '-h "Cache-Control:private, max-age=0, no-transform"'
      - "rsync"
      - "-r"
      - "-c"
      - "-d"
      - "./public"
      - "gs://jonmessdaily.com"
