steps:
  - name: node
    entrypoint: npm
    args: ["install"]
  - name: node
    entrypoint: npm
    args: ["run", "build"]
  - name: gcr.io/cloud-builders/gsutil
    args:
      - "-m"
      - "rsync"
      - "-r"
      - "-c"
      - "-d"
      - "./public/"
      - "gs://jonmessdaily.com"


const auth = new google.auth.GoogleAuth({
          // Scopes can be specified either as an array or as a single, space-delimited string.
          scopes: ['https://www.googleapis.com/auth/cloud-platform'],
        });
     
        // Acquire an auth client, and bind it to all future calls
        const authClient = await auth.getClient();
        google.options('auth', authClient);
     
        // Do the magic
        const res = await cloudbuild.projects.builds.list({
          // The raw filter text to constrain the results.
          filter: 'placeholder-value',
          // Number of results to return in the list.
          pageSize: 'placeholder-value',
          // Token to provide to skip to a particular spot in the list.
          pageToken: 'placeholder-value',
          // Required. ID of the project.
          projectId: 'placeholder-value',
        });
        console.log(res.data)